global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - /usr/local/etc/prometheus/bkcp.rules.yml

scrape_configs:
  - job_name: bkcp
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
          - 127.0.0.1:9188
        labels:
          service: bkcp
