#!/bin/sh

prefix="/usr/local"

kea_dhcp4_config_file="/usr/local/etc/kea/kea-dhcp4.conf"
kea_dhcp6_config_file="/usr/local/etc/kea/kea-dhcp6.conf"
kea_dhcp_ddns_config_file="/usr/local/etc/kea/kea-dhcp-ddns.conf"
kea_netconf_config_file="/usr/local/etc/kea/kea-netconf.conf"

exec_prefix="/usr/local"
dhcp4_srv="/usr/local/sbin/kea-dhcp4"
dhcp6_srv="/usr/local/sbin/kea-dhcp6"
dhcp_ddns_srv="/usr/local/sbin/kea-dhcp-ddns"
netconf_srv="/usr/local/sbin/kea-netconf"

dhcp4_cli_options=""
dhcp6_cli_options=""
dhcp_ddns_cli_options=""
netconf_cli_options=""

dhcp4=yes
dhcp6=no
dhcp_ddns=no
netconf=no
kea_verbose=no
