#!/bin/sh
set -eu

SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)

CLUSTER_NODE_PREFIX="${CLUSTER_NODE_PREFIX:-${JAIL_NODE_PREFIX:-jail-node}}"
CLUSTER_NODE_COUNT="${CLUSTER_NODE_COUNT:-${JAIL_NODE_COUNT:-3}}"
CLUSTER_PROFILE_FILE="${CLUSTER_PROFILE_FILE:-${FREEBSD_JAIL_PROFILE_FILE:-${SCRIPT_DIR}/../config/cloud-init/freebsd-jail-node.yaml}}"
KUBECTL_BOOTSTRAP="${KUBECTL_BOOTSTRAP:-no}"

export CLUSTER_NODE_PREFIX CLUSTER_NODE_COUNT CLUSTER_PROFILE_FILE KUBECTL_BOOTSTRAP
exec sh "${SCRIPT_DIR}/freebsd_cluster.sh" up
