#!/bin/sh

# PROVIDE: stork_agent
# REQUIRE: LOGIN stork_server kea NETWORKING
# KEYWORD: shutdown

# shellcheck source=/dev/null
. /etc/rc.subr

name="stork_agent"
rcvar="stork_agent_enable"

load_rc_config "$name"

: "${stork_agent_enable:=NO}"
: "${stork_agent_env_file:=/usr/local/etc/stork/agent.env}"
: "${stork_agent_log_file:=/var/log/stork/agent.log}"

pidfile="/var/run/${name}.pid"
stork_agent_binary="/usr/local/bin/stork-agent"
command="/usr/sbin/daemon"
procname="/usr/sbin/daemon"
command_args="-r -P ${pidfile} -T ${name} -u stork-agent -o ${stork_agent_log_file} ${stork_agent_binary} --use-env-file --env-file=${stork_agent_env_file}"
required_files="${stork_agent_binary} ${stork_agent_env_file}"

run_rc_command "$1"
